### ISSUE TITLE
DLR for Xamarin

### ISSUE THREAD

**Issue by stdcppdev** [IronLanguages/dlr#152]
Hi all,
I'm an app developer and I've tried to add IronPython reference to Xamarin project.
The NuGet prompts the following incompatible messages.
Will DLR support Xamarin project in the future? Guess it will be a quite great feature.
Thanks for your great work!

================================================================
Installing DynamicLanguageRuntime 1.2.2.
NU1202: Package DynamicLanguageRuntime 1.2.2 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package DynamicLanguageRuntime 1.2.2 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)

**Comment by slide** [comment]
Once netstandard2.1 is out, we will reevaluate if the needed APIs are there.
