### ISSUE TITLE
.Net Standard support

### ISSUE THREAD

**Issue by YairHalberstadt** [IronLanguages/dlr#175]
Are there any plans to support .Net Standard in the future?
.Net Core and .Net Framework are already supported, so I'm guessing this shouldn't be impossible.

Thanks for all your great work on IronPython - it's really appreciated, and we use it heavily for our plugin system. Unfortunately that's currently holding us back from porting our application to .Net Standard...

**Comment by YairHalberstadt** [comment]
I spent about half an hour to see if this could be done simply.

Some of the required Reflection.Emit APIs are missing such as DynamicMethod and TypeBuilder.CreateType()

However given that in most cases a .Net Standard library will either be used on .Net Framework or .Net Core, I think it might be worth targeting .Net Standard so that cross platform libraries can use it without needing to multitarget, and throwing a NotSupportedException if used on an AOT platform where Reflection.Emit is not supported.

**Comment by slozier** [comment]
There was a bit of back and forth related to using the Reflection.Emit package. It looks like Microsoft finally settled on having a .NET Standard 2.0 version of the package (even if it throws) so I would be fine with having one as well.

**Comment by slozier** [comment]
Resolved by https://github.com/IronLanguages/dlr/pull/176
