### ISSUE TITLE
Drop support for Silverlight?

### ISSUE THREAD

**Issue by gpetrou** [IronLanguages/dlr#24]
As in https://github.com/IronLanguages/ironpython2/issues/14 is the plan to drop Silverlight here as well?
If yes, I could try to add a PR.

**Comment by slozier** [comment]
I think Silverlight is already excluded from this repo? Feel free to take a look if you think something should be cleaned up though.

**Comment by gpetrou** [comment]
I am referring to preprocessor symbols, such as "SILVERLIGHT" and "WP75". Should these be removed?

**Comment by slozier** [comment]
Yes, we can remove those.

**Comment by slide** [comment]
Isn't this closed via #32?

**Comment by gpetrou** [comment]
There are a few more Silverlight items. I will do one more PR. Should I remove CLR2 as well or this is still needed?

**Comment by slide** [comment]
CLR2 can go as well
