### ISSUE TITLE
Dynamic null exception in other service.

### ISSUE THREAD

**Issue by nobyArdor** [IronLanguages/dlr#95]
Good time of day. 

I am not sure, it is right place to ask, by I'll try.

I develop plugin in C# for soft develop another company. 
And sometimes my plugin crush with error 

System.NullReferenceException: Object reference not set to an instance of an object. 
  at System.Dynamic.ExcepInfo.GetException() 
  at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message).

I suggest that can be result of execution 92 and 93 lines in https://github.com/IronLanguages/dlr/blob/master/Src/Microsoft.Dynamic/ComInterop/ExcepInfo.cs
in case exception is null.
Please, could you recommend way to intercept  "internal Exception GetException()" in runtime to see "ExcepInfo" fields and "message" if it exists before plugin crush? 
Could you suggest way to prevent this error raise or method execution change in runtime?

P. S. Sorry for my bad spelling.
With best regars,
Gorbunov Ivan.

**Comment by gpetrou** [comment]
Do you have any small code sample that would reproduce this?

**Comment by slide** [comment]
System.Dynamic is a library released by Microsoft. You'd want to raise an issue with them for that library. It will be different from this library.
